/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AccountNameIndexImport } from './routes/$accountName.index'
import { Route as AccountNameCharacterNameIndexImport } from './routes/$accountName.$characterName.index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AccountNameIndexRoute = AccountNameIndexImport.update({
  id: '/$accountName/',
  path: '/$accountName/',
  getParentRoute: () => rootRoute,
} as any)

const AccountNameCharacterNameIndexRoute =
  AccountNameCharacterNameIndexImport.update({
    id: '/$accountName/$characterName/',
    path: '/$accountName/$characterName/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$accountName/': {
      id: '/$accountName/'
      path: '/$accountName'
      fullPath: '/$accountName'
      preLoaderRoute: typeof AccountNameIndexImport
      parentRoute: typeof rootRoute
    }
    '/$accountName/$characterName/': {
      id: '/$accountName/$characterName/'
      path: '/$accountName/$characterName'
      fullPath: '/$accountName/$characterName'
      preLoaderRoute: typeof AccountNameCharacterNameIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$accountName': typeof AccountNameIndexRoute
  '/$accountName/$characterName': typeof AccountNameCharacterNameIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$accountName': typeof AccountNameIndexRoute
  '/$accountName/$characterName': typeof AccountNameCharacterNameIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$accountName/': typeof AccountNameIndexRoute
  '/$accountName/$characterName/': typeof AccountNameCharacterNameIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$accountName' | '/$accountName/$characterName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$accountName' | '/$accountName/$characterName'
  id: '__root__' | '/' | '/$accountName/' | '/$accountName/$characterName/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountNameIndexRoute: typeof AccountNameIndexRoute
  AccountNameCharacterNameIndexRoute: typeof AccountNameCharacterNameIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountNameIndexRoute: AccountNameIndexRoute,
  AccountNameCharacterNameIndexRoute: AccountNameCharacterNameIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$accountName/",
        "/$accountName/$characterName/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$accountName/": {
      "filePath": "$accountName.index.tsx"
    },
    "/$accountName/$characterName/": {
      "filePath": "$accountName.$characterName.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
