/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountNameIndexRouteImport } from './routes/$accountName/index'
import { Route as AccountNameCharacterNameIndexRouteImport } from './routes/$accountName/$characterName/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountNameIndexRoute = AccountNameIndexRouteImport.update({
  id: '/$accountName/',
  path: '/$accountName/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountNameCharacterNameIndexRoute =
  AccountNameCharacterNameIndexRouteImport.update({
    id: '/$accountName/$characterName/',
    path: '/$accountName/$characterName/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$accountName': typeof AccountNameIndexRoute
  '/$accountName/$characterName': typeof AccountNameCharacterNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$accountName': typeof AccountNameIndexRoute
  '/$accountName/$characterName': typeof AccountNameCharacterNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$accountName/': typeof AccountNameIndexRoute
  '/$accountName/$characterName/': typeof AccountNameCharacterNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$accountName' | '/$accountName/$characterName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$accountName' | '/$accountName/$characterName'
  id: '__root__' | '/' | '/$accountName/' | '/$accountName/$characterName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountNameIndexRoute: typeof AccountNameIndexRoute
  AccountNameCharacterNameIndexRoute: typeof AccountNameCharacterNameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$accountName/': {
      id: '/$accountName/'
      path: '/$accountName'
      fullPath: '/$accountName'
      preLoaderRoute: typeof AccountNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$accountName/$characterName/': {
      id: '/$accountName/$characterName/'
      path: '/$accountName/$characterName'
      fullPath: '/$accountName/$characterName'
      preLoaderRoute: typeof AccountNameCharacterNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountNameIndexRoute: AccountNameIndexRoute,
  AccountNameCharacterNameIndexRoute: AccountNameCharacterNameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
